### ISSUE TITLE
Create front-end form to collect tree registrations

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#10]
A few approaches here:
- we could build something totally custom (https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/wiki/Create-New-Posts-Post-Type-Entries-Using-A-Front-End-Form)
  Pros: total control
  Cons: probably the most time-consuming option; requires re-inventing the wheel
- we could use the [CMB2 plugin](https://github.com/WebDevStudios/CMB2) to build something custom: https://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/
  Pros: free, full-featured, more control, doesn't allow for front-end editing of form, nice [Google maps add-on](https://github.com/mustardBees/cmb_field_map)
  Cons: a bit more work to get up & running
- we could use [Gravity Forms](http://www.gravityforms.com/): https://yoast.com/gravity-forms-custom-post-types/
  Pros: lots of [add-ons](http://www.gravityforms.com/add-ons/), [Mailchimp integration](http://www.gravityforms.com/add-ons/mailchimp/), can be used to [post to a CPT](https://en-gb.wordpress.org/plugins/gravity-forms-custom-post-types/)
  Cons: paid, allows for front-end editing of form, not as much control 

Features that would be nice here:
- form submission creates a new CPT post in draft status
- site admin will need to review each submission and approve/publish the CPT post
- post author would default to the logged-in user if available, otherwise fall back to a user with the email address given, and if that doesn’t work, create a new user with the email address
- alternately, we could skip the post author altogether, since this isn't super important (ie we don't need a facility to edit registrations, at least right now?)
- submission would NOT require signup
- [honeypot](https://solutionfactor.net/blog/2014/02/01/honeypot-technique-fast-easy-spam-prevention/) spam protection
- site admins should be notified when there are new submissions & prompted to review & publish

**Comment by michiecat** [comment]
My $0.2 -- I think Gravity forms would be the best option to start with, since it would involve less "reinventing the wheel" and it seems to cover most (all?) of the desired functionality.

**Comment by Justonetree** [comment]
Not sure what they are, but you're the pro so will 
trust your judgement.

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by Justonetree** [comment]
I'm not sure of the implication of these 3 choices 
and probably need more information and perhaps the 
face-to-face with Michelle. However, key factors 
for us are:

1)  it needs to automatically update the map (# of 
trees) & the treemometer (2 different plugins now, 
I think) (we could ditch the treemometer and have 
another goal marker, but what's better than a tree 
for us?)

2)  ideally sorts the trees by neighborhood (we 
need easy access to the list of trees)

3)  easy for us (even me!) to update content and 
ideally change front page Key Info and Titles as 
needed

4)  We don't need people to be able to comment on 
our website; they should be able to send a comment 
when they sign up or have an address for email 
communication

Google maps did not work for us because it located 
dots by address and people don't want their 
address visible to the public.

What does 'paid' mean, both $$ amount and whether 
there is something monthly;  we definitely don't 
want the latter if at all possible or no more than 
$10/month at max.

Kindly Reply All so Nicole sees our 
communication.  Thanks very much.  Isabel

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by sarahmonster** [comment]
https://justonetree.mystagingwebsite.com/got-a-tree/register-your-tree/

Uses Gravity Forms.
