### ISSUE TITLE
Develop tree-o-meter functionality

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/just-one-tree#2]
The tree-o-meter is a running tally of all trees registered and is an important bit of custom functionality for the new site.

From #1:

> The treemometer, which should count the trees registered automatically; the map on the home page has a tree count on it and that should automatically be updated. I think there are 3 places where there is a tree count and they all should say the same number ! We could ditch the treemometer but some cute element (that is automatically updated) where people can check on progress toward the sustainability goal would be good. 

In short, we need to keep a running tally of trees registered that we can then programmatically display elsewhere in the theme. It might be worth considering storing tree registrations as a custom post type, so all data with respect to tree registrations is stored within WordPress, but this would depend on the functional requirements here.

@Justonetree how do you currently store this number? It looks as though trees are registered via a Google form here: http://justonetree.org/got-a-tree-2/register-your-tree/. Do you have a spreadsheet that is populated via that form, or does the form just send an email with the registration information?

**Comment by Justonetree** [comment]
Not sure what I am supposed to do

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by sarahmonster** [comment]
Hi Isabel! Can you give me some details about how the current tree registration process works? I'm just trying to figure out what you currently have in place, so we can build a system that works for you.

It looks as though registering a tree goes to a Google form. When a user fills out that form to register a tree, where is that information sent? Is the information stored somewhere automatically, or do you just receive an email with the data? How do you access all the information about tree registrations?

**Comment by Justonetree** [comment]
I thought that one depository was in a file on my 
computer but the ones there are old (all the 
original ones) and I don't see any new ones.  Not 
sure how (or if you want at this point) to send 
these to you.  Have another list on Mail Chimp, 
also not current. My 'techie' helper figured out 
how to grab these names from somewhere on my 
computer I think, but not sure where yet.  I have 
found 2 files on Google drive, but neither with 
the full set of registered tree owners.  I see the 
Share button for those, so I can send them if you 
want.

I am reviewing emails from Green Info consultant 
because it may provide locational information.  I 
always need help working with any of this stuff;  
and there are no long-term volunteers to help me 
find anything!  Sorry- will hopefully get what you 
need today.

Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992

**Comment by Justonetree** [comment]
Hi Sarah,

I'm wondering about your progress on our website?  
We're anxious to get it together as soon as 
possible to fit with our big push this fall?  We 
just received a small grant to help us with 
outreach;  would some funding help us push our 
site up on your docket?  We totally appreciate 
your effort to date and understand you need to 
make a living too.  I just don't want to get into 
a situation like last year where I spent about 
$2000 'fixing' our old website and then it didn't 
work correctly- and that wasn't even a re-do!  
Kindly let me know what is the best plan here for 
you.  Thanks very much.  Isabel


-- 
Isabel Wade
Just One Tree, Chief Lemon Ambassador
415-601-6992
