### ISSUE TITLE
Put background color in header that shows when featured images are small?

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#35]
Is this intentional for how featured images look that are smaller than the minimum width? 

<img width="1070" alt="screen shot 2017-01-13 at 11 41 39 pm" src="https://cloud.githubusercontent.com/assets/1385492/21953450/42a83dd8-d9ec-11e6-8f02-aa9ef32e0218.png">

If it's intentional please ignore but I think it would look cleaner with a solid background color, maybe the pale yellow from the treeometer?

**Comment by sarahmonster** [comment]
It's definitely my hope/aim here that featured images will be uploaded at much larger sizes in the future—but since so many of the old posts do use super-teeny featured images, I'll need to account for this. (Ideally I can check for the image size before using the featured image in the header to make sure it's big enough, and only use images that are of a suitable dimension.)
