### ISSUE TITLE
Border between left and right columns on interior pages?

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#38]
I love the layout, however I feel that there could be a subtle vertical border or some other sort of visual element between the left and right columns on the interior pages ... I feel like that would set off the sections a bit more. To me it feels like there's a bit of white space between the two columns, especially near the top and a subtle line could help break it up some...it doesn't even need to extend all the way down. Again, this is a personal preference so feel free to ignore. :)

**Comment by sarahmonster** [comment]
I thought about this for a while and I think the issue is that the sidebar can feel a bit unanchored, particularly because its widgets are a bit sparse. 

Adding a left-hand border is a bit awkward. A better solution is to use titles for the widgets, and style them so the title fills the full width, like so:

<img width="1141" alt="screenshot 2017-01-19 21 11 08" src="https://cloud.githubusercontent.com/assets/376315/22125505/d43c8882-de8b-11e6-9ce3-b545fb9e2b60.png">
