### ISSUE TITLE
Just One Tree header text not centered on mobile

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#39]
Is this intentional? I actually think it would look nice centered:

<img width="390" alt="screen shot 2017-01-14 at 12 18 22 am" src="https://cloud.githubusercontent.com/assets/1385492/21953540/0dc74ac0-d9ef-11e6-9b06-3417850b7df0.png">

**Comment by sarahmonster** [comment]
Thanks for catching this! This looks like it's due to Chrome rendering the text below the logo, rather than beside it (which is how Firefox arranges it and how it was originally intended to work.)

That said, I think it may work nicely having the logo & text stacked even on smaller screens, rather than side-by side, so long as it doesn't eat up too much of the header space.
