### ISSUE TITLE
Suggestion: fleurons around "Recent Updates" section title

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#47]
This could tie that section in with the rest of the front page headers.

**Comment by sarahmonster** [comment]
Thanks for the feedback! I don't think the fleurons work here—they take up a lot of space and require a centre, rather than left-hand, alignment, which makes things feel a bit more disconnected. I have extended the widget title styling to this block, which I think is the best I can do, barring more extensive structural changes.

Ultimately I think the awkwardness here is caused by trying to jam too much disparate stuff into a small(ish) space. I'll revisit post-launch, when I expect there will be some content adjustments to be done anyway.
