### ISSUE TITLE
Could lists inside post/page content have more left margin?

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/just-one-tree#62]
I think a little more left margin is needed for bulleted lists inside the post/page content. See http://justonetree.org/about-2/partners/ for an example.

**Comment by sarahmonster** [comment]
The bullets sit in the gutter on purpose—this is actually typographically correct, because it means the bullets don't impede the flow of reading the text. It's just harder to do online and in software programmes, so we're used to seeing lists un-hung, even though they should really be hung.

More information/explanation: http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2

**Comment by michiecat** [comment]
Thanks @sarahmonster for the explanation, I learned something new today!
